const functions = require('firebase-functions');
const admin = require('firebase-admin');

// (originalName)(_999x999)(.jpg)
const sourceExp = /previews\/(.+)_([0-9]+)x([0-9]+)(\..{3,4})/

// updates the firebase document for this upload with information about
// the preview images generated by the resize images extension
exports.default = functions.storage.object().onFinalize(async (object) => {
    if (!(object.metadata || {}).resizedImage) {
        return;
    }

    const storageRef = admin.storage().bucket().file(object.name);
    console.log(storageRef);
    console.log(JSON.stringify(storageRef));

    const [_, name, width, height, extension] = sourceExp.exec(object.name);
    const sourceName = `${name}${extension}`;
    const sourceDoc = admin.firestore().doc(`uploads/${sourceName}`);

    try {
        sourceDoc.update({
            [`previews.${width}x${height}`]: {
                path: object.name,
                width,
                height,
                // downloadURL: storageRef.getDownloadURL()
            }
        })
    }
    catch (e) {
        console.error(e);
    }
});
